-- ============================================================
-- Context-aware frame and interaction model (ADR-021)
--
-- Existing CAPCOM / UFD / SuperCombo tables remain source-of-truth snapshots.
-- These additive tables provide canonical move identity and condition-bound
-- observations.  They are intentionally empty until a reviewed backfill or
-- importer writes evidence-backed rows.
--
-- Apply: Supabase Studio -> SQL Editor
-- Rollback order:
--   combo_link_observations, move_transition_observations,
--   punish_observations, move_geometry_samples, interaction_observations,
--   system_rule_observations, frame_observations, canonical_move_aliases,
--   move_source_links, canonical_moves
-- ============================================================

-- 1. One identity per executable move variant.  Same input may have several
-- variants (hold, install, stance, drink level), so variant_key is mandatory.
CREATE TABLE IF NOT EXISTS canonical_moves (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_slug      text NOT NULL,
  canonical_input     text,
  canonical_name      text NOT NULL,
  move_kind           text NOT NULL CHECK (move_kind IN (
                        'normal', 'command_normal', 'throw', 'special', 'super',
                        'drive', 'movement', 'followup', 'other'
                      )),
  variant_key         text NOT NULL DEFAULT 'base',
  variant_conditions  jsonb NOT NULL DEFAULT '{}'::jsonb,
  valid_from_patch    text,
  valid_to_patch      text,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  identity_key        text GENERATED ALWAYS AS (
                        coalesce(canonical_input, 'name:' || lower(canonical_name))
                        || '|variant:' || variant_key
                      ) STORED,
  UNIQUE (character_slug, identity_key)
);

CREATE INDEX IF NOT EXISTS idx_canonical_moves_character_input
  ON canonical_moves (character_slug, canonical_input);
CREATE INDEX IF NOT EXISTS idx_canonical_moves_variant_conditions
  ON canonical_moves USING gin (variant_conditions);

-- 2. Evidence links from a canonical identity to each raw-source row.
CREATE TABLE IF NOT EXISTS move_source_links (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_move_id   bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  source              text NOT NULL CHECK (source IN (
                        'capcom', 'ufd', 'supercombo', 'community', 'manual_test'
                      )),
  source_record_key   text NOT NULL,
  source_move_name    text,
  source_input        text,
  source_url          text,
  match_method        text NOT NULL,
  match_confidence    numeric(5,4) NOT NULL CHECK (
                        match_confidence >= 0 AND match_confidence <= 1
                      ),
  match_evidence      jsonb NOT NULL DEFAULT '{}'::jsonb,
  reviewed            boolean NOT NULL DEFAULT false,
  observed_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, source_record_key, canonical_move_id)
);

CREATE INDEX IF NOT EXISTS idx_move_source_links_move
  ON move_source_links (canonical_move_id, source);

-- 3. Natural-language aliases point to a canonical variant, not a family row.
-- Family-level aliases may set requires_variant_clarification=true and leave
-- canonical_move_id NULL until the user supplies strength/hold/state details.
CREATE TABLE IF NOT EXISTS canonical_move_aliases (
  id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_slug                  text NOT NULL,
  alias                           text NOT NULL,
  alias_normalized                text NOT NULL,
  locale                          text NOT NULL DEFAULT 'ja',
  canonical_move_id               bigint REFERENCES canonical_moves(id) ON DELETE CASCADE,
  family_key                      text,
  alias_conditions                jsonb NOT NULL DEFAULT '{}'::jsonb,
  requires_variant_clarification  boolean NOT NULL DEFAULT false,
  source                          text NOT NULL DEFAULT 'manual',
  confidence                      numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                                    confidence >= 0 AND confidence <= 1
                                  ),
  reviewed                        boolean NOT NULL DEFAULT false,
  created_at                      timestamptz NOT NULL DEFAULT now(),
  CHECK (canonical_move_id IS NOT NULL OR family_key IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_canonical_move_aliases_lookup
  ON canonical_move_aliases (character_slug, locale, alias_normalized);
CREATE UNIQUE INDEX IF NOT EXISTS uq_canonical_move_aliases_target
  ON canonical_move_aliases (
    character_slug, locale, alias_normalized,
    coalesce(canonical_move_id, 0), coalesce(family_key, '')
  );

-- 4. A frame value is an observation plus explicit conditions.  Ranges and
-- stage sequences are not flattened to the first integer.
CREATE TABLE IF NOT EXISTS frame_observations (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_move_id       bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  source_link_id          bigint REFERENCES move_source_links(id) ON DELETE SET NULL,
  field                   text NOT NULL CHECK (field IN (
                            'startup', 'active', 'recovery', 'total', 'on_block',
                            'on_hit', 'hitstun', 'blockstun', 'damage', 'range'
                          )),
  perspective             text NOT NULL DEFAULT 'attacker' CHECK (perspective IN (
                            'attacker', 'defender', 'system', 'not_applicable'
                          )),
  value_kind              text NOT NULL CHECK (value_kind IN (
                            'scalar', 'range', 'alternatives', 'stage_sequence',
                            'active_sequence', 'composite', 'knockdown',
                            'not_applicable', 'variable', 'missing'
                          )),
  value_num               numeric,
  min_num                 numeric,
  max_num                 numeric,
  structured_value        jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_value               text,
  conditions              jsonb NOT NULL DEFAULT '{}'::jsonb,
  condition_key           text NOT NULL DEFAULT 'default',
  calculation_policy      text NOT NULL DEFAULT 'observed' CHECK (calculation_policy IN (
                            'observed', 'derived', 'display_only', 'not_usable'
                          )),
  derivation              jsonb NOT NULL DEFAULT '{}'::jsonb,
  usable_for_calculation  boolean NOT NULL DEFAULT false,
  valid_from_patch        text,
  valid_to_patch          text,
  observed_at             timestamptz,
  evidence_url            text,
  confidence              numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                            confidence >= 0 AND confidence <= 1
                          ),
  reviewed                boolean NOT NULL DEFAULT false,
  created_at              timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (value_kind = 'scalar' AND value_num IS NOT NULL)
    OR value_kind <> 'scalar'
  ),
  CHECK (
    (value_kind = 'range' AND min_num IS NOT NULL AND max_num IS NOT NULL AND min_num <= max_num)
    OR value_kind <> 'range'
  )
);

CREATE INDEX IF NOT EXISTS idx_frame_observations_move_field
  ON frame_observations (canonical_move_id, field, valid_from_patch);
CREATE INDEX IF NOT EXISTS idx_frame_observations_conditions
  ON frame_observations USING gin (conditions);
CREATE UNIQUE INDEX IF NOT EXISTS uq_frame_observations_identity
  ON frame_observations (
    canonical_move_id, coalesce(source_link_id, 0), field, perspective,
    condition_key, coalesce(valid_from_patch, '')
  );

-- 5. Patch-scoped mechanics such as Burnout or Drive Rush modifiers.  Bot code
-- must not hard-code a modifier if an active, reviewed rule is absent.
CREATE TABLE IF NOT EXISTS system_rule_observations (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_key          text NOT NULL,
  applies_to_field  text NOT NULL,
  operation         text NOT NULL CHECK (operation IN (
                      'add_frames', 'set_frames', 'multiply', 'state_transition',
                      'eligibility', 'other'
                    )),
  value_num         numeric,
  structured_value  jsonb NOT NULL DEFAULT '{}'::jsonb,
  conditions        jsonb NOT NULL DEFAULT '{}'::jsonb,
  condition_key     text NOT NULL DEFAULT 'default',
  source            text NOT NULL,
  evidence_url      text,
  valid_from_patch  text,
  valid_to_patch    text,
  confidence        numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                      confidence >= 0 AND confidence <= 1
                    ),
  reviewed          boolean NOT NULL DEFAULT false,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_system_rule_observations_active
  ON system_rule_observations (rule_key, valid_from_patch, reviewed);
CREATE INDEX IF NOT EXISTS idx_system_rule_observations_conditions
  ON system_rule_observations USING gin (conditions);
CREATE UNIQUE INDEX IF NOT EXISTS uq_system_rule_observations_identity
  ON system_rule_observations (
    rule_key, condition_key, coalesce(valid_from_patch, ''), source
  );

-- 6. Observed contact results bind spacing/state to an actual frame outcome.
CREATE TABLE IF NOT EXISTS interaction_observations (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attacker_move_id          bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  defender_character_slug   text NOT NULL,
  interaction               text NOT NULL CHECK (interaction IN ('block', 'hit', 'whiff')),
  contact_active_frame      integer CHECK (contact_active_frame IS NULL OR contact_active_frame > 0),
  stage_index               integer CHECK (stage_index IS NULL OR stage_index > 0),
  pre_contact_distance      numeric,
  post_contact_distance     numeric,
  distance_unit             text,
  attacker_position         text CHECK (attacker_position IS NULL OR attacker_position IN (
                              'midscreen', 'near_corner', 'corner'
                            )),
  defender_state            text CHECK (defender_state IS NULL OR defender_state IN (
                              'standing', 'crouching', 'airborne', 'knockdown'
                            )),
  counter_state             text CHECK (counter_state IS NULL OR counter_state IN (
                              'normal', 'counter', 'punish_counter'
                            )),
  defender_burnout          boolean,
  drive_rush_kind           text CHECK (drive_rush_kind IS NULL OR drive_rush_kind IN (
                              'raw', 'cancel'
                            )),
  attacker_advantage_f      integer,
  result_state              jsonb NOT NULL DEFAULT '{}'::jsonb,
  source                    text NOT NULL,
  evidence_url              text,
  evidence_storage_path     text,
  patch_version             text,
  confidence                numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                              confidence >= 0 AND confidence <= 1
                            ),
  reviewed                  boolean NOT NULL DEFAULT false,
  observed_at               timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_interaction_observations_lookup
  ON interaction_observations (
    attacker_move_id, defender_character_slug, interaction, patch_version
  );

-- 7. UFD GIFs stay in Storage.  Machine-readable per-frame hit/hurt/push boxes
-- and reach measurements are stored here only after an extraction/review step.
CREATE TABLE IF NOT EXISTS move_geometry_samples (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canonical_move_id     bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  animation_frame       integer NOT NULL CHECK (animation_frame > 0),
  sample_type           text NOT NULL CHECK (sample_type IN (
                          'hitbox', 'hurtbox', 'pushbox', 'throwbox', 'origin', 'reach'
                        )),
  coordinate_system     text NOT NULL,
  geometry              jsonb NOT NULL DEFAULT '{}'::jsonb,
  forward_reach         numeric,
  source_asset_path     text,
  source_asset_sha256   text,
  extraction_method     text NOT NULL,
  confidence            numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                          confidence >= 0 AND confidence <= 1
                        ),
  reviewed              boolean NOT NULL DEFAULT false,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_move_geometry_samples_move_frame
  ON move_geometry_samples (canonical_move_id, animation_frame, sample_type);
CREATE UNIQUE INDEX IF NOT EXISTS uq_move_geometry_samples_identity
  ON move_geometry_samples (
    canonical_move_id, animation_frame, sample_type,
    coalesce(source_asset_sha256, ''), extraction_method
  );

-- 8. Direct matchup verification is the strongest evidence for a confirmed
-- punish and remains useful even before GIF geometry extraction is reliable.
CREATE TABLE IF NOT EXISTS punish_observations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blocked_move_id       bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  punisher_move_id      bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  scenario              jsonb NOT NULL DEFAULT '{}'::jsonb,
  scenario_key          text NOT NULL,
  frame_window_f        integer,
  reached               boolean NOT NULL,
  punish_confirmed      boolean NOT NULL,
  failure_reason        text,
  test_protocol         text,
  source                text NOT NULL,
  evidence_url          text,
  evidence_storage_path text,
  patch_version         text,
  confidence            numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                          confidence >= 0 AND confidence <= 1
                        ),
  reviewed              boolean NOT NULL DEFAULT false,
  observed_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_punish_observations_lookup
  ON punish_observations (
    blocked_move_id, punisher_move_id, patch_version, reviewed
  );
CREATE INDEX IF NOT EXISTS idx_punish_observations_scenario
  ON punish_observations USING gin (scenario);
CREATE UNIQUE INDEX IF NOT EXISTS uq_punish_observations_identity
  ON punish_observations (
    blocked_move_id, punisher_move_id, scenario_key,
    coalesce(patch_version, ''), source
  );

-- 9. Legal move-to-move transitions.  Hit advantage alone cannot prove a
-- cancel, chain, stance follow-up or juggle route, so those rules are stored
-- as patch-scoped, evidence-backed graph edges.
CREATE TABLE IF NOT EXISTS move_transition_observations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_move_id        bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  target_move_id        bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  transition_type       text NOT NULL CHECK (transition_type IN (
                          'link', 'chain', 'cancel', 'drive_rush_cancel',
                          'target_combo', 'stance_followup', 'juggle', 'other'
                        )),
  on_interaction        text NOT NULL DEFAULT 'hit' CHECK (on_interaction IN (
                          'hit', 'block', 'whiff', 'any'
                        )),
  window_start_f        integer CHECK (window_start_f IS NULL OR window_start_f >= 0),
  window_end_f          integer CHECK (window_end_f IS NULL OR window_end_f >= 0),
  required_state        jsonb NOT NULL DEFAULT '{}'::jsonb,
  resulting_state       jsonb NOT NULL DEFAULT '{}'::jsonb,
  resource_cost         jsonb NOT NULL DEFAULT '{}'::jsonb,
  conditions            jsonb NOT NULL DEFAULT '{}'::jsonb,
  condition_key         text NOT NULL DEFAULT 'default',
  source                text NOT NULL,
  evidence_url          text,
  patch_version         text,
  confidence            numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                          confidence >= 0 AND confidence <= 1
                        ),
  reviewed              boolean NOT NULL DEFAULT false,
  created_at            timestamptz NOT NULL DEFAULT now(),
  CHECK (
    window_start_f IS NULL OR window_end_f IS NULL
    OR window_start_f <= window_end_f
  )
);

CREATE INDEX IF NOT EXISTS idx_move_transition_observations_source
  ON move_transition_observations (
    source_move_id, on_interaction, transition_type, patch_version, reviewed
  );
CREATE INDEX IF NOT EXISTS idx_move_transition_observations_conditions
  ON move_transition_observations USING gin (conditions);
CREATE UNIQUE INDEX IF NOT EXISTS uq_move_transition_observations_identity
  ON move_transition_observations (
    source_move_id, target_move_id, transition_type, on_interaction,
    condition_key, coalesce(patch_version, ''), source
  );

-- 10. Direct A -> B combo tests are stronger than a timing-only inference and
-- preserve why a route succeeds or fails under a concrete hit scenario.
CREATE TABLE IF NOT EXISTS combo_link_observations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  starter_move_id       bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  followup_move_id      bigint NOT NULL REFERENCES canonical_moves(id) ON DELETE CASCADE,
  scenario              jsonb NOT NULL DEFAULT '{}'::jsonb,
  scenario_key          text NOT NULL,
  transition_type       text NOT NULL CHECK (transition_type IN (
                          'link', 'chain', 'cancel', 'drive_rush_cancel',
                          'target_combo', 'stance_followup', 'juggle', 'other'
                        )),
  timing_connected      boolean,
  spatial_connected     boolean,
  state_connected       boolean,
  combo_confirmed       boolean NOT NULL,
  gap_f                 integer,
  failure_reason        text,
  result_state          jsonb NOT NULL DEFAULT '{}'::jsonb,
  test_protocol         text,
  source                text NOT NULL,
  evidence_url          text,
  evidence_storage_path text,
  patch_version         text,
  confidence            numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                          confidence >= 0 AND confidence <= 1
                        ),
  reviewed              boolean NOT NULL DEFAULT false,
  observed_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_combo_link_observations_lookup
  ON combo_link_observations (
    starter_move_id, followup_move_id, patch_version, reviewed
  );
CREATE INDEX IF NOT EXISTS idx_combo_link_observations_scenario
  ON combo_link_observations USING gin (scenario);
CREATE UNIQUE INDEX IF NOT EXISTS uq_combo_link_observations_identity
  ON combo_link_observations (
    starter_move_id, followup_move_id, transition_type, scenario_key,
    coalesce(patch_version, ''), source
  );

-- Read access matches the existing frame-data tables.  Importers and review
-- tools write with service_role, which bypasses RLS.
ALTER TABLE canonical_moves             ENABLE ROW LEVEL SECURITY;
ALTER TABLE move_source_links           ENABLE ROW LEVEL SECURITY;
ALTER TABLE canonical_move_aliases      ENABLE ROW LEVEL SECURITY;
ALTER TABLE frame_observations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_rule_observations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE interaction_observations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE move_geometry_samples       ENABLE ROW LEVEL SECURITY;
ALTER TABLE punish_observations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE move_transition_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE combo_link_observations      ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'canonical_moves', 'move_source_links', 'canonical_move_aliases',
    'frame_observations', 'system_rule_observations',
    'interaction_observations', 'move_geometry_samples', 'punish_observations',
    'move_transition_observations', 'combo_link_observations'
  ]
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "public read" ON %I', table_name);
    EXECUTE format(
      'CREATE POLICY "public read" ON %I FOR SELECT TO anon, authenticated USING (true)',
      table_name
    );
  END LOOP;
END $$;
