-- ============================================================
-- Multi-move sequence observations (ADR-022)
--
-- Apply after contextual_frame_model_migration.sql.
-- This migration is additive. Existing source tables and observations remain
-- unchanged.
-- ============================================================

-- SuperCombo already stores hitstop. Allow reviewed normalized observations to
-- retain it instead of leaving the value only in the raw source table.
DO $$
BEGIN
  IF to_regclass('public.frame_observations') IS NOT NULL THEN
    ALTER TABLE frame_observations
      DROP CONSTRAINT IF EXISTS frame_observations_field_check;
    ALTER TABLE frame_observations
      ADD CONSTRAINT frame_observations_field_check CHECK (field IN (
        'startup', 'active', 'recovery', 'total', 'on_block', 'on_hit',
        'hitstun', 'blockstun', 'hitstop', 'damage', 'range'
      ));
  END IF;
END $$;

-- One row captures a reviewed result for an event sequence. The JSON event
-- representation permits future movement, delay, armor and projectile events
-- without flattening them into a single move. Canonical move ids may be stored
-- inside each event after canonical_moves is backfilled; source input remains
-- mandatory for portability during the transition.
CREATE TABLE IF NOT EXISTS sequence_observations (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  observation_key           text NOT NULL,
  attacker_character_slug   text NOT NULL,
  attacker_sequence         jsonb NOT NULL,
  initial_interaction       text NOT NULL CHECK (
                              initial_interaction IN ('block', 'hit')
                            ),
  defender_character_slug   text,
  defender_move_input       text,
  defender_profile          jsonb NOT NULL DEFAULT '{}'::jsonb,
  outcome                   text NOT NULL CHECK (outcome IN (
                              'trade', 'attacker_hit', 'defender_hit', 'block',
                              'whiff', 'clash', 'unresolved'
                            )),
  attacker_advantage_f      integer,
  defender_advantage_f      integer,
  confirmed_followups       jsonb NOT NULL DEFAULT '[]'::jsonb,
  result_state              jsonb NOT NULL DEFAULT '{}'::jsonb,
  conditions                jsonb NOT NULL DEFAULT '{}'::jsonb,
  source                    text NOT NULL,
  evidence_url              text,
  evidence_storage_path     text,
  test_protocol             text,
  patch_version             text NOT NULL,
  confidence                numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                              confidence >= 0 AND confidence <= 1
                            ),
  reviewed                  boolean NOT NULL DEFAULT false,
  observed_at               timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  CHECK (jsonb_typeof(attacker_sequence) = 'array'),
  CHECK (jsonb_array_length(attacker_sequence) >= 2),
  CHECK (jsonb_typeof(confirmed_followups) = 'array'),
  CHECK (
    (defender_character_slug IS NULL AND defender_move_input IS NULL)
    OR (defender_character_slug IS NOT NULL AND defender_move_input IS NOT NULL)
  ),
  CHECK (
    attacker_advantage_f IS NULL OR defender_advantage_f IS NULL
    OR attacker_advantage_f = -defender_advantage_f
  ),
  CHECK (
    NOT reviewed
    OR (
      attacker_advantage_f IS NULL
      AND defender_advantage_f IS NULL
      AND jsonb_array_length(confirmed_followups) = 0
    )
    OR (
      defender_character_slug IS NOT NULL
      AND defender_move_input IS NOT NULL
    )
  ),
  UNIQUE (observation_key, source, patch_version)
);

CREATE INDEX IF NOT EXISTS idx_sequence_observations_attacker
  ON sequence_observations (
    attacker_character_slug, initial_interaction, outcome, patch_version, reviewed
  );
CREATE INDEX IF NOT EXISTS idx_sequence_observations_sequence
  ON sequence_observations USING gin (attacker_sequence);
CREATE INDEX IF NOT EXISTS idx_sequence_observations_defender_profile
  ON sequence_observations USING gin (defender_profile);
CREATE INDEX IF NOT EXISTS idx_sequence_observations_conditions
  ON sequence_observations USING gin (conditions);

ALTER TABLE sequence_observations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read" ON sequence_observations;
CREATE POLICY "public read" ON sequence_observations
  FOR SELECT TO anon, authenticated USING (true);

COMMENT ON TABLE sequence_observations IS
  'Reviewed multi-event outcomes used by deterministic sequence analysis.';
