-- ============================================================
-- Source-addressable transition rules (ADR-030)
--
-- ``canonical_moves`` is intentionally not backfilled yet, while SuperCombo
-- already has stable (character, input) keys.  Keep reviewed timing edges in
-- this additive table so every character can be covered before canonical IDs
-- exist.  A later canonical backfill can link or migrate these rows without
-- changing the Bot's rule semantics.
--
-- Apply: Supabase Studio -> SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS source_transition_rules (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_slug        text NOT NULL,
  source_input          text NOT NULL,
  target_input          text NOT NULL,
  transition_type       text NOT NULL CHECK (transition_type IN (
                          'chain', 'cancel', 'drive_rush_cancel',
                          'target_combo', 'stance_followup', 'juggle', 'other'
                        )),
  initial_interaction   text NOT NULL DEFAULT 'block' CHECK (
                          initial_interaction IN ('block', 'hit', 'whiff', 'any')
                        ),
  -- ``direct_block_gap`` means the rule provides the time from defender
  -- actionable to target first active.  A NULL min with max=0 records a
  -- direct true-blockstring statement without inventing a negative gap.
  timing_basis          text NOT NULL CHECK (timing_basis IN (
                          'direct_block_gap', 'manual_timing_window'
                        )),
  timing_reference      text NOT NULL CHECK (timing_reference IN (
                          'defender_actionable', 'hitstop_end'
                        )),
  gap_min_f             integer,
  gap_max_f             integer,
  conditions            jsonb NOT NULL DEFAULT '{}'::jsonb,
  condition_key         text NOT NULL DEFAULT 'default',
  source                text NOT NULL,
  evidence              text,
  evidence_url          text,
  patch_version         text,
  confidence            numeric(5,4) NOT NULL DEFAULT 1 CHECK (
                          confidence >= 0 AND confidence <= 1
                        ),
  reviewed              boolean NOT NULL DEFAULT false,
  reviewed_at           timestamptz,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  CHECK (
    gap_min_f IS NULL OR gap_max_f IS NULL OR gap_min_f <= gap_max_f
  ),
  CHECK (
    timing_basis <> 'direct_block_gap'
    OR gap_max_f IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_source_transition_rules_lookup
  ON source_transition_rules (
    character_slug, source_input, target_input, initial_interaction,
    reviewed, patch_version
  );
CREATE INDEX IF NOT EXISTS idx_source_transition_rules_conditions
  ON source_transition_rules USING gin (conditions);
CREATE UNIQUE INDEX IF NOT EXISTS uq_source_transition_rules_identity
  ON source_transition_rules (
    character_slug, source_input, target_input, transition_type,
    initial_interaction, condition_key, coalesce(patch_version, ''), source
  );

ALTER TABLE source_transition_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public read" ON source_transition_rules;
CREATE POLICY "public read" ON source_transition_rules
  FOR SELECT TO anon, authenticated USING (true);

COMMENT ON TABLE source_transition_rules IS
  'Reviewed SuperCombo-addressable transition timing rules. Runtime ignores unreviewed candidates.';
